name: Site Pessoal
favicon: null
layout_spectrum: 0.01514
typography_spectrum: 0.5949339144863188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e50010'
    - '#000000'
    - '#ec5456'
    - '#afafaf'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
